POST http://localhost:3000/uploads/file
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImVtYWlsIjoicnVsb3NAZ21haWwuY29tIiwiaWF0IjoxNzkxMzk3ODYyLCJleHAiOjE3OTE0MDE0NjIsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.S_Xqq5ctcUEhUrDdPYkriVWYloFZxx9qag-GMYZMHXo
Content-Type: multipart/form-data; boundary=----FormBoundary

------FormBoundary
Content-Disposition: form-data; name="file"; filename="marcelaRd.jpeg"
Content-Type: image/jpeg

< ./marcelaRd.jpeg
------FormBoundary--