GET http://localhost:3000/users/me
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImVtYWlsIjoicnVsb3NAZ21haWwuY29tIiwiaWF0IjoxNzg1NTIyNjUyLCJleHAiOjE3ODU1MjYyNTIsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.UqnMCMsxTrw01LrPLaDujaK4QKDG3sardOyUgMN0mTY
