export enum PlaceType {
  HISTORICAL = 'HISTORICAL',
  MUSEUM = 'MUSEUM',
  PARK = 'PARK',
  NEIGHBORHOOD = 'NEIGHBORHOOD',
  MARKET = 'MARKET',
  RESTAURANT = 'RESTAURANT',
  BAR = 'BAR',
  SALSA_CLUB = 'SALSA_CLUB',
  CULTURAL = 'CULTURAL',
  OTHER = 'OTHER',
}
